name: Pylint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip --no-cache-dir
          pip install --no-cache-dir -r requirements.txt pylint

      - name: Run Pylint and enforce score
        id: pylint
        run: |
          pylint_output=$(pylint $(git ls-files '*.py'))
          echo "$pylint_output"
          score=$(echo "$pylint_output" | grep "Your code has been rated at" | awk '{print $7}' | cut -d'/' -f1)
          echo "Pylint score: $score"
          # Fail if score < 9
          awk -v score="$score" 'BEGIN { if (score < 9) exit 1; }'
